### ISSUE TITLE
Is Magic Onion supported?

### ISSUE THREAD

**Issue by KAW0** [Cysharp/GrpcWebSocketBridge#1]
Following errors with MagicOnion 
![obraz](https://user-images.githubusercontent.com/16373327/171503162-8f3aeeff-0986-483f-9b78-e55d6d6eb89f.png)

**Comment by KAW0** [comment]
Ok adding USE_GRPC_NET_CLIENT_ONLY fixed problem. I belive it should be mentioned in the documentation.

**Comment by mayuki** [comment]
Sorry for the lack of documentation, projects that do not include C-core will need to specify that constant.
We will update the README. Thank you.
