### ISSUE TITLE
Custom SSL Cert

### ISSUE THREAD

**Issue by ken1437** [Cysharp/GrpcWebSocketBridge#11]
does it support custom ssl cert?

**Comment by mayuki** [comment]
The server can be configured in ASP.NET Core (Kestrel) or reverse proxy.
On the client, you can use any certificate that HttpClient can handle.

**Comment by mwegner** [comment]
Would it be possible to expose Unity's [Networking.CertificateHandler](https://docs.unity3d.com/ScriptReference/Networking.CertificateHandler.html) cleanly with the GrpcWebSocketBridge setup?

Our use case is to essentially disable cert checks for development builds.
