### ISSUE TITLE
Why MagicOnionSampleApp.Shared is Targeting netstandard 2.0?

### ISSUE THREAD

**Issue by Sen-Gupta** [Cysharp/GrpcWebSocketBridge#12]
Hello,

I am looking at MagicOnion for first time so please excuse my ignorance.

Do we need to target  netstandard 2.0 everywhere where we add package MagicOnion.Abstractions?

My intent is to use MagicOnion with BlazorWebAssembly and MAUI both?

Can we use MagicOnion Client in MAUI apps?

Thanks

**Comment by mayuki** [comment]
MagicOnion client supports various platforms such as .NET Framework, .NET Core, and Unity.
To support different frameworks on the client and server, the target of the shared code project is `netstandard2.0`.

For example, Unity supports only .NET Standard 2.0 or 2.1.
If the client is .NET MAUI app, it is possible to target `net6.0` in the shared code project.

**Comment by Sen-Gupta** [comment]
Thank you so much!

I recently saw the new MemoryPack, is there an implementation of memory pack sample available with .net 7 blazor for dummies like us?
