### ISSUE TITLE
WebGL biuld doesn't work

### ISSUE THREAD

**Issue by KAW0** [Cysharp/GrpcWebSocketBridge#2]
This method in `Grpc.Net.Client.Internal.OperatingSystem`
`private OperatingSystem()
{
    this.IsBrowser = RuntimeInformation.IsOSPlatform(OSPlatform.Create("browser"));
}`
is affected by this bug:
https://issuetracker.unity3d.com/issues/notsupportedexception-thrown-when-calling-any-member-of-system-dot-runtime-dot-interopservices-dot-runtimeinformation-in-webgl
and throw exception when calling `GrpcChannel.ForAddress`
Since this project already use modified `Grpc.Net.Client` only for WebGL I recommend to change this line to:
`this.IsBrowser = true;`

**Comment by mayuki** [comment]
Sorry for the late reply. We have confirmed this issue and would like to address it.

**Comment by mayuki** [comment]
Thanks! We have released a version 1.1.0.
https://github.com/Cysharp/GrpcWebSocketBridge/releases/tag/1.1.0
