### ISSUE TITLE
1.1.0 broke MagicOnionService

### ISSUE THREAD

**Issue by miv** [Cysharp/GrpcWebSocketBridge#6]
Env:

Unity 2021.3.5.f1

Problem:

After 1.1.0 MagicOnionService (not StreamingHub) stopped working with error on client - "No grpc-status found on response".

How to reproduce:

Add any Service to MagicOnion sample and try using 

```
var service = MagicOnionClient.Create<IMyService>(channel); 
await service.MyMethod();
```

Hack fix:

In 1.1.0 some api has been changed to native api where possible if unity can support it. 

Somehow returning `TrailingHeadersHelpers.TrailingHeaders` to previous version fixes the problem.

**Comment by mayuki** [comment]
This is due to the change of the code for Unity 2021.3 is now for .NET Standard 2.1.
As a result, Grpc.Net.Client assembly must also be used for .NET Standard 2.1, but we do not publish custom builds at this time.

We will publish a custom Grpc.Net.Client build. We apologize for the inconvenience.
